const jobArchiveData = [
  {
    Id: "71A80D30-7991-43EA-AF51-0691F0BB23E1",
    Name: "MLA_NMABQ2002_31LEA",
    Operation: 24,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-01T15:58:53.1004442",
    InitializingTimeUtc: "2024-10-01T15:59:01.8688886",
    ChunksQueuedTimeUtc: "2024-10-01T15:59:02.0370000",
    RunningTimeUtc: "2024-10-01T15:59:10.6870000",
    AllChunksPushedTimeUtc: "2024-10-01T15:59:16.1260000",
    StoppingTimeutc: "2024-10-01T15:59:16.1770000",
    EndTimeUtc: "2024-10-01T15:59:16.1935190",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 1,
    ChunksRequeuedAtLeastOnce: 0,
    ChunksRequeuedAtLeastTwice: 0,
    ChunksSucceeded: 1,
    ChunksSkipped: 0,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 5438,
    MaxChunkCompletionMs: 5438,
    AvgChunkCompletionMs: 5438,
    MedianChunkCompletionMs: 5438,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitCellLoadJobMessage","CellLoadingDatabaseAlias":"ctl","WhereClause":"WHERE SectorId=\\u0027MLA_NMABQ2002_31LEA\\u0027","Force":true,"OutputRasterDirectory":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\CellLoadSignalRepository","Reprojections":[{"Epsg":4326,"Resolution_Meters":100,"ExportTIFF":false,"Native":false}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id": "71a80d30-7991-43ea-af51-0691f0bb23e1","Operation":"CellLoad","Name":"MLA_NMABQ2002_31LEA","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":null,"NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"CellLoadJobResponseMessage","CellsAttempted":1,"CellsLoaded":1,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "7A142C8A-AA25-475E-866C-07FF38C43D7C",
    Name: "dropfile",
    Operation: 3,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-01T20:18:48.2849675",
    InitializingTimeUtc: "2024-10-01T20:18:55.8399077",
    ChunksQueuedTimeUtc: "2024-10-01T20:20:22.0500000",
    RunningTimeUtc: "2024-10-01T20:20:29.1970000",
    AllChunksPushedTimeUtc: "2024-10-01T20:20:41.1960000",
    StoppingTimeutc: "2024-10-01T20:20:41.4210000",
    EndTimeUtc: "2024-10-01T20:20:41.6209057",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 8,
    ChunksRequeuedAtLeastOnce: 0,
    ChunksRequeuedAtLeastTwice: 0,
    ChunksSucceeded: 8,
    ChunksSkipped: 0,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 1358,
    MaxChunkCompletionMs: 1685,
    AvgChunkCompletionMs: 1492,
    MedianChunkCompletionMs: 1406,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitDropFileLoadJobMessage","DeleteSourceOnSuccess":false,"DropFileParsingPatterns":["(?i)(?\\u003Cmarket\\u003E[A-Z0-9]\\u002B)_(?\\u003Ctechnology\\u003E[A-Z0-9]\\u002B)_(?\\u003Cband\\u003E[A-Z0-9]\\u002B)\\\\.grd$"],"OutputRasterDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","DropDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\DropFileLoad","TagId":1,"Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id": "7a142c8a-aa25-475e-866c-07ff38c43d7c","Operation":"DropFileLoad","Name":"dropfile","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"DropFileJobResponseMessage","GrdFileCount":13,"ChunkCount":8,"FailedChunkCount":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "7808273B-4551-4253-B3BF-2B8F61C4D76E",
    Name: "dropfile",
    Operation: 3,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-01T20:30:38.6970120",
    InitializingTimeUtc: "2024-10-01T20:30:38.8973442",
    ChunksQueuedTimeUtc: "2024-10-01T20:30:39.2630000",
    RunningTimeUtc: "2024-10-01T20:30:48.3970000",
    AllChunksPushedTimeUtc: "2024-10-01T20:33:47.5050000",
    StoppingTimeutc: "2024-10-01T20:33:48.4920000",
    EndTimeUtc: "2024-10-01T20:33:48.5866076",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 8,
    ChunksRequeuedAtLeastOnce: 0,
    ChunksRequeuedAtLeastTwice: 0,
    ChunksSucceeded: 8,
    ChunksSkipped: 0,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 1636,
    MaxChunkCompletionMs: 109629,
    AvgChunkCompletionMs: 22382,
    MedianChunkCompletionMs: 1636,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitDropFileLoadJobMessage","DeleteSourceOnSuccess":false,"DropFileParsingPatterns":["(?i)(?\\u003Cmarket\\u003E[A-Z0-9]\\u002B)_(?\\u003Ctechnology\\u003E[A-Z0-9]\\u002B)_(?\\u003Cband\\u003E[A-Z0-9]\\u002B)\\\\.grd$"],"OutputRasterDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","DropDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\DropFileLoad","TagId":1,"Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id": "7808273b-4551-4253-b3bf-2b8f61c4d76e","Operation":"DropFileLoad","Name":"dropfile","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"DropFileJobResponseMessage","GrdFileCount":13,"ChunkCount":8,"FailedChunkCount":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "E0FEF820-76E5-45E1-8508-335AD8C24BF6",
    Name: "dropfile",
    Operation: 3,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-01T21:10:18.2521479",
    InitializingTimeUtc: "2024-10-01T21:10:25.2185407",
    ChunksQueuedTimeUtc: "2024-10-01T21:10:25.4380000",
    RunningTimeUtc: "2024-10-01T21:10:35.0340000",
    AllChunksPushedTimeUtc: "2024-10-01T21:10:51.8890000",
    StoppingTimeutc: "2024-10-01T21:10:51.9190000",
    EndTimeUtc: "2024-10-01T21:10:52.0592521",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 8,
    ChunksRequeuedAtLeastOnce: 0,
    ChunksRequeuedAtLeastTwice: 0,
    ChunksSucceeded: 8,
    ChunksSkipped: 0,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 2036,
    MaxChunkCompletionMs: 2210,
    AvgChunkCompletionMs: 2102,
    MedianChunkCompletionMs: 2036,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitDropFileLoadJobMessage","DeleteSourceOnSuccess":false,"DropFileParsingPatterns":["(?i)(?\\u003Cmarket\\u003E[A-Z0-9]\\u002B)_(?\\u003Ctechnology\\u003E[A-Z0-9]\\u002B)_(?\\u003Cband\\u003E[A-Z0-9]\\u002B)\\\\.grd$"],"OutputRasterDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","DropDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\DropFileLoad","TagId":1,"Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id": "e0fef820-76e5-45e1-8508-335ad8c24bf6","Operation":"DropFileLoad","Name":"dropfile","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"DropFileJobResponseMessage","GrdFileCount":13,"ChunkCount":8,"FailedChunkCount":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "FD330844-8C3A-4D75-82B7-457A218C670F",
    Name: "MLA_NMABQ2002_31LEA",
    Operation: 24,
    Priority: 1,
    Status: 1,
    AllChunksPushed: false,
    SubmitTimeUtc: "2024-10-01T15:39:49.1628303",
    Owner: "Richard.O@sgsi.com",
    RequestJson:
      '{"$type":"SubmitCellLoadJobMessage","CellLoadingDatabaseAlias":"ctl","WhereClause":"WHERE SectorId=\\u0027MLA_NMABQ2002_31LEA\\u0027","Force":false,"OutputRasterDirectory":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\CellLoadSignalRepository","Reprojections":[{"Epsg":4326,"Resolution_Meters":100,"ExportTIFF":false,"Native":false}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id":"fd330844-8c3a-4d75-82b7-457a218c670f","Operation":"CellLoad","Name":"MLA_NMABQ2002_31LEA","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":null,"NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
  },
  {
    Id: "20633CD7-F446-4708-A220-4B325DD674CD",
    Name: "dropfile",
    Operation: 3,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-01T20:22:24.3959650",
    InitializingTimeUtc: "2024-10-01T20:22:42.0303949",
    ChunksQueuedTimeUtc: "2024-10-01T20:23:35.2070000",
    RunningTimeUtc: "2024-10-01T20:23:45.2110000",
    AllChunksPushedTimeUtc: "2024-10-01T20:24:07.6150000",
    StoppingTimeutc: "2024-10-01T20:24:07.9010000",
    EndTimeUtc: "2024-10-01T20:24:08.0172184",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 8,
    ChunksRequeuedAtLeastOnce: 0,
    ChunksRequeuedAtLeastTwice: 0,
    ChunksSucceeded: 8,
    ChunksSkipped: 0,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 2600,
    MaxChunkCompletionMs: 3021,
    AvgChunkCompletionMs: 2791,
    MedianChunkCompletionMs: 2947,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitDropFileLoadJobMessage","DeleteSourceOnSuccess":false,"DropFileParsingPatterns":["(?i)(?\\u003Cmarket\\u003E[A-Z0-9]\\u002B)_(?\\u003Ctechnology\\u003E[A-Z0-9]\\u002B)_(?\\u003Cband\\u003E[A-Z0-9]\\u002B)\\\\.grd$"],"OutputRasterDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","DropDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\DropFileLoad","TagId":1,"Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id": "20633cd7-f446-4708-a220-4b325dd674cd","Operation":"DropFileLoad","Name":"dropfile","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"DropFileJobResponseMessage","GrdFileCount":13,"ChunkCount":8,"FailedChunkCount":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "1D888826-8FD7-43CA-A623-61AAC9E8F299",
    Name: "dropfile",
    Operation: 3,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-01T21:07:04.7315017",
    InitializingTimeUtc: "2024-10-01T21:07:13.9286873",
    ChunksQueuedTimeUtc: "2024-10-01T21:07:14.2250000",
    RunningTimeUtc: "2024-10-01T21:07:23.9680000",
    AllChunksPushedTimeUtc: "2024-10-01T21:10:04.9650000",
    StoppingTimeutc: "2024-10-01T21:10:04.9950000",
    EndTimeUtc: "2024-10-01T21:10:05.1288383",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 8,
    ChunksRequeuedAtLeastOnce: 0,
    ChunksRequeuedAtLeastTwice: 0,
    ChunksSucceeded: 8,
    ChunksSkipped: 0,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 1964,
    MaxChunkCompletionMs: 112054,
    AvgChunkCompletionMs: 20112,
    MedianChunkCompletionMs: 2381,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitDropFileLoadJobMessage","DeleteSourceOnSuccess":false,"DropFileParsingPatterns":["(?i)(?\\u003Cmarket\\u003E[A-Z0-9]\\u002B)_(?\\u003Ctechnology\\u003E[A-Z0-9]\\u002B)_(?\\u003Cband\\u003E[A-Z0-9]\\u002B)\\\\.grd$"],"OutputRasterDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","DropDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\DropFileLoad","TagId":1,"Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id": "1d888826-8fd7-43ca-a623-61aac9e8f299","Operation":"DropFileLoad","Name":"dropfile","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"DropFileJobResponseMessage","GrdFileCount":13,"ChunkCount":8,"FailedChunkCount":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "3A422D1A-8D02-4B7F-A705-624AA4F92DD8",
    Name: "MLA_NMABQ2002_31LEA",
    Operation: 24,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-01T15:53:10.2452031",
    InitializingTimeUtc: "2024-10-01T15:53:19.2119882",
    ChunksQueuedTimeUtc: "2024-10-01T15:53:29.9330000",
    RunningTimeUtc: "2024-10-01T15:53:39.8670000",
    AllChunksPushedTimeUtc: "2024-10-01T15:53:40.0780000",
    StoppingTimeutc: "2024-10-01T15:53:41.0430000",
    EndTimeUtc: "2024-10-01T15:53:41.0714772",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 1,
    ChunksRequeuedAtLeastOnce: 0,
    ChunksRequeuedAtLeastTwice: 0,
    ChunksSucceeded: 1,
    ChunksSkipped: 0,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 210,
    MaxChunkCompletionMs: 210,
    AvgChunkCompletionMs: 210,
    MedianChunkCompletionMs: 210,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitCellLoadJobMessage","CellLoadingDatabaseAlias":"ctl","WhereClause":"WHERE SectorId=\\u0027MLA_NMABQ2002_31LEA\\u0027","Force":true,"OutputRasterDirectory":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\CellLoadSignalRepository","Reprojections":[{"Epsg":4326,"Resolution_Meters":100,"ExportTIFF":false,"Native":false}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id":"3a422d1a-8d02-4b7f-a705-624aa4f92dd8","Operation":"CellLoad","Name":"MLA_NMABQ2002_31LEA","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":null,"NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"CellLoadJobResponseMessage","CellsAttempted":1,"CellsLoaded":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "91514C48-11C2-46AB-AA47-66E4C319AD1F",
    Name: "dropfile",
    Operation: 3,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-01T16:47:23.5070972",
    InitializingTimeUtc: "2024-10-01T16:47:23.5668976",
    ChunksQueuedTimeUtc: "2024-10-01T16:48:36.3470000",
    RunningTimeUtc: "2024-10-01T16:48:46.3580000",
    AllChunksPushedTimeUtc: "2024-10-01T16:48:59.5880000",
    StoppingTimeutc: "2024-10-01T16:48:59.7420000",
    EndTimeUtc: "2024-10-01T16:48:59.8412171",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 8,
    ChunksRequeuedAtLeastOnce: 0,
    ChunksRequeuedAtLeastTwice: 0,
    ChunksSucceeded: 8,
    ChunksSkipped: 0,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 1449,
    MaxChunkCompletionMs: 2261,
    AvgChunkCompletionMs: 1645,
    MedianChunkCompletionMs: 1699,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitDropFileLoadJobMessage","DeleteSourceOnSuccess":false,"DropFileParsingPatterns":["(?i)(?\\u003Cmarket\\u003E[A-Z0-9]\\u002B)_(?\\u003Ctechnology\\u003E[A-Z0-9]\\u002B)_(?\\u003Cband\\u003E[A-Z0-9]\\u002B)\\\\.grd$"],"OutputRasterDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","DropDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\DropFileLoad","TagId":1,"Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id":"91514c48-11c2-46ab-aa47-66e4c319ad1f","Operation":"DropFileLoad","Name":"dropfile","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"DropFileJobResponseMessage","GrdFileCount":13,"ChunkCount":8,"FailedChunkCount":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "3E1C90F0-A049-4034-BE44-68A8736AA24B",
    Name: "dropfile",
    Operation: 3,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: false,
    SubmitTimeUtc: "2024-10-01T16:45:56.7827062",
    InitializingTimeUtc: "2024-10-01T16:46:03.3126641",
    ChunksQueuedTimeUtc: "2024-10-01T16:46:03.3440000",
    StoppingTimeutc: "2024-10-01T16:46:03.3570000",
    EndTimeUtc: "2024-10-01T16:46:03.3774466",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 0,
    RequestJson:
      '{"$type":"SubmitDropFileLoadJobMessage","DeleteSourceOnSuccess":false,"DropFileParsingPatterns":["(?i)(?\\u003Cmarket\\u003E[A-Z0-9]\\u002B)_(?\\u003Ctechnology\\u003E[A-Z0-9]\\u002B)_(?\\u003Cband\\u003E[A-Z0-9]\\u002B)\\\\.grd$"],"OutputRasterDirectory":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\DropFileLoadSignalRepository\\\\","DropDirectory":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\DropFileLoadDrop\\\\","TagId":1,"Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id":"3e1c90f0-a049-4034-be44-68a8736aa24b","Operation":"DropFileLoad","Name":"dropfile","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\DropFileLoadSignalRepository\\\\","NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"DropFileJobResponseMessage","GrdFileCount":0,"ChunkCount":0,"FailedChunkCount":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "3B439152-D437-4FB2-84C7-743CAD897019",
    Name: "dropfile",
    Operation: 3,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-01T19:44:14.0030617",
    InitializingTimeUtc: "2024-10-01T19:44:25.9648822",
    ChunksQueuedTimeUtc: "2024-10-01T19:55:23.8330000",
    RunningTimeUtc: "2024-10-01T19:55:31.8070000",
    AllChunksPushedTimeUtc: "2024-10-01T19:55:42.8140000",
    StoppingTimeutc: "2024-10-01T19:55:43.1810000",
    EndTimeUtc: "2024-10-01T19:55:43.2556326",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 8,
    ChunksRequeuedAtLeastOnce: 0,
    ChunksRequeuedAtLeastTwice: 0,
    ChunksSucceeded: 8,
    ChunksSkipped: 0,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 1292,
    MaxChunkCompletionMs: 1453,
    AvgChunkCompletionMs: 1369,
    MedianChunkCompletionMs: 1453,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitDropFileLoadJobMessage","DeleteSourceOnSuccess":false,"DropFileParsingPatterns":["(?i)(?\\u003Cmarket\\u003E[A-Z0-9]\\u002B)_(?\\u003Ctechnology\\u003E[A-Z0-9]\\u002B)_(?\\u003Cband\\u003E[A-Z0-9]\\u002B)\\\\.grd$"],"OutputRasterDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","DropDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\DropFileLoad","TagId":1,"Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id": "3b439152-d437-4fb2-84c7-743cad897019","Operation":"DropFileLoad","Name":"dropfile","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"DropFileJobResponseMessage","GrdFileCount":13,"ChunkCount":8,"FailedChunkCount":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "A094752B-58D1-46B0-85F6-79C12E5A6943",
    Name: "dropfile",
    Operation: 3,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-01T20:20:29.7444710",
    InitializingTimeUtc: "2024-10-01T20:20:41.6646761",
    ChunksQueuedTimeUtc: "2024-10-01T20:22:19.2980000",
    RunningTimeUtc: "2024-10-01T20:22:29.2750000",
    AllChunksPushedTimeUtc: "2024-10-01T20:22:41.5270000",
    StoppingTimeutc: "2024-10-01T20:22:41.8760000",
    EndTimeUtc: "2024-10-01T20:22:41.9835519",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 8,
    ChunksRequeuedAtLeastOnce: 0,
    ChunksRequeuedAtLeastTwice: 0,
    ChunksSucceeded: 8,
    ChunksSkipped: 0,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 1337,
    MaxChunkCompletionMs: 1823,
    AvgChunkCompletionMs: 1526,
    MedianChunkCompletionMs: 1364,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitDropFileLoadJobMessage","DeleteSourceOnSuccess":false,"DropFileParsingPatterns":["(?i)(?\\u003Cmarket\\u003E[A-Z0-9]\\u002B)_(?\\u003Ctechnology\\u003E[A-Z0-9]\\u002B)_(?\\u003Cband\\u003E[A-Z0-9]\\u002B)\\\\.grd$"],"OutputRasterDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","DropDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\DropFileLoad","TagId":1,"Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id": "a094752b-58d1-46b0-85f6-79c12e5a6943","Operation":"DropFileLoad","Name":"dropfile","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"DropFileJobResponseMessage","GrdFileCount":13,"ChunkCount":8,"FailedChunkCount":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "AD4DDF09-CA7E-4C94-BAA4-8017F483F5B1",
    Name: "dropfile",
    Operation: 3,
    Priority: 1,
    Status: 3,
    AllChunksPushed: false,
    SubmitTimeUtc: "2024-10-01T20:59:40.0887346",
    InitializingTimeUtc: "2024-10-01T20:59:48.1995604",
    ChunksQueuedTimeUtc: "2024-10-01T20:59:48.4180000",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 8,
    RequestJson:
      '{"$type":"SubmitDropFileLoadJobMessage","DeleteSourceOnSuccess":false,"DropFileParsingPatterns":["(?i)(?\\u003Cmarket\\u003E[A-Z0-9]\\u002B)_(?\\u003Ctechnology\\u003E[A-Z0-9]\\u002B)_(?\\u003Cband\\u003E[A-Z0-9]\\u002B)\\\\.grd$"],"OutputRasterDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","DropDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\DropFileLoad","TagId":1,"Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id": "ad4ddf09-ca7e-4c94-baa4-8017f483f5b1","Operation":"DropFileLoad","Name":"dropfile","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "58F88F1B-D45B-482A-A32A-83A33DB3D137",
    Name: "dropfile",
    Operation: 3,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-01T21:12:40.2957797",
    InitializingTimeUtc: "2024-10-01T21:12:50.2283386",
    ChunksQueuedTimeUtc: "2024-10-01T21:12:50.4510000",
    RunningTimeUtc: "2024-10-01T21:13:00.2480000",
    AllChunksPushedTimeUtc: "2024-10-01T21:14:21.5690000",
    StoppingTimeutc: "2024-10-01T21:14:22.1050000",
    EndTimeUtc: "2024-10-01T21:14:22.2213523",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 8,
    ChunksRequeuedAtLeastOnce: 0,
    ChunksRequeuedAtLeastTwice: 0,
    ChunksSucceeded: 8,
    ChunksSkipped: 0,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 2157,
    MaxChunkCompletionMs: 38403,
    AvgChunkCompletionMs: 10155,
    MedianChunkCompletionMs: 2177,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitDropFileLoadJobMessage","DeleteSourceOnSuccess":false,"DropFileParsingPatterns":["(?i)(?\\u003Cmarket\\u003E[A-Z0-9]\\u002B)_(?\\u003Ctechnology\\u003E[A-Z0-9]\\u002B)_(?\\u003Cband\\u003E[A-Z0-9]\\u002B)\\\\.grd$"],"OutputRasterDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","DropDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\DropFileLoad","TagId":1,"Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":null,"Maintained":"\\u003E= 0%","Degraded":"\\u003C= 50%","Dropped":null},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id":"58f88f1b-d45b-482a-a32a-83a33db3d137","Operation":"DropFileLoad","Name":"dropfile","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"DropFileJobResponseMessage","GrdFileCount":13,"ChunkCount":8,"FailedChunkCount":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "B78C73D5-43A9-4094-A5AE-938256FAF3CF",
    Name: "MLA_NMABQ2002_31LEA",
    Operation: 24,
    Priority: 1,
    Status: 1,
    AllChunksPushed: false,
    SubmitTimeUtc: "2024-10-01T15:42:03.9012794",
    Owner: "Richard.O@sgsi.com",
    RequestJson:
      '{"$type":"SubmitCellLoadJobMessage","CellLoadingDatabaseAlias":"ctl","WhereClause":"WHERE SectorId=\\u0027MLA_NMABQ2002_31LEA\\u0027","Force":false,"OutputRasterDirectory":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\CellLoadSignalRepository","Reprojections":[{"Epsg":4326,"Resolution_Meters":100,"ExportTIFF":false,"Native":false}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id": "b78c73d5-43a9-4094-a5ae-938256faf3cf","Operation":"CellLoad","Name":"MLA_NMABQ2002_31LEA","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":null,"NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
  },
  {
    Id: "3A71D98A-5FAA-495C-A50E-976FCCDAE30E",
    Name: "dropfile",
    Operation: 3,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-01T19:20:56.3104705",
    InitializingTimeUtc: "2024-10-01T19:21:01.6396375",
    ChunksQueuedTimeUtc: "2024-10-01T19:21:11.2740000",
    RunningTimeUtc: "2024-10-01T19:21:11.7200000",
    AllChunksPushedTimeUtc: "2024-10-01T19:33:08.8790000",
    StoppingTimeutc: "2024-10-01T19:33:09.4710000",
    EndTimeUtc: "2024-10-01T19:33:09.5687611",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 8,
    ChunksRequeuedAtLeastOnce: 0,
    ChunksRequeuedAtLeastTwice: 0,
    ChunksSucceeded: 8,
    ChunksSkipped: 0,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 1245,
    MaxChunkCompletionMs: 698474,
    AvgChunkCompletionMs: 89637,
    MedianChunkCompletionMs: 1311,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitDropFileLoadJobMessage","DeleteSourceOnSuccess":false,"DropFileParsingPatterns":["(?i)(?\\u003Cmarket\\u003E[A-Z0-9]\\u002B)_(?\\u003Ctechnology\\u003E[A-Z0-9]\\u002B)_(?\\u003Cband\\u003E[A-Z0-9]\\u002B)\\\\.grd$"],"OutputRasterDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","DropDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\DropFileLoad","TagId":1,"Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id":"3a71d98a-5faa-495c-a50e-976fccdae30e","Operation":"DropFileLoad","Name":"dropfile","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"DropFileJobResponseMessage","GrdFileCount":13,"ChunkCount":8,"FailedChunkCount":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "27C3951A-97D9-4827-B1F9-9B4D1203FECE",
    Name: "dropfile",
    Operation: 3,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-01T19:40:35.9009886",
    InitializingTimeUtc: "2024-10-01T19:40:41.3418873",
    ChunksQueuedTimeUtc: "2024-10-01T19:44:04.4060000",
    RunningTimeUtc: "2024-10-01T19:44:14.4110000",
    AllChunksPushedTimeUtc: "2024-10-01T19:44:25.5330000",
    StoppingTimeutc: "2024-10-01T19:44:25.8590000",
    EndTimeUtc: "2024-10-01T19:44:25.9339859",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 8,
    ChunksRequeuedAtLeastOnce: 0,
    ChunksRequeuedAtLeastTwice: 0,
    ChunksSucceeded: 8,
    ChunksSkipped: 0,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 1301,
    MaxChunkCompletionMs: 1448,
    AvgChunkCompletionMs: 1384,
    MedianChunkCompletionMs: 1374,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitDropFileLoadJobMessage","DeleteSourceOnSuccess":false,"DropFileParsingPatterns":["(?i)(?\\u003Cmarket\\u003E[A-Z0-9]\\u002B)_(?\\u003Ctechnology\\u003E[A-Z0-9]\\u002B)_(?\\u003Cband\\u003E[A-Z0-9]\\u002B)\\\\.grd$"],"OutputRasterDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","DropDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\DropFileLoad","TagId":1,"Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id": "27c3951a-97d9-4827-b1f9-9b4d1203fece","Operation":"DropFileLoad","Name":"dropfile","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"DropFileJobResponseMessage","GrdFileCount":13,"ChunkCount":8,"FailedChunkCount":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "30097EC1-E1D8-4162-A2BC-9CCD364BFEC7",
    Name: "MLA_NMABQ2002_31LEA",
    Operation: 24,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: false,
    SubmitTimeUtc: "2024-10-01T15:48:40.4119650",
    InitializingTimeUtc: "2024-10-01T15:48:50.2820153",
    ChunksQueuedTimeUtc: "2024-10-01T15:50:58.8270000",
    StoppingTimeutc: "2024-10-01T15:50:58.8540000",
    EndTimeUtc: "2024-10-01T15:50:58.8844235",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 0,
    RequestJson:
      '{"$type":"SubmitCellLoadJobMessage","CellLoadingDatabaseAlias":"ctl","WhereClause":"WHERE SectorId=\\u0027MLA_NMABQ2002_31LEA\\u0027","Force":false,"OutputRasterDirectory":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\CellLoadSignalRepository","Reprojections":[{"Epsg":4326,"Resolution_Meters":100,"ExportTIFF":false,"Native":false}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id":"30097ec1-e1d8-4162-a2bc-9ccd364bfec7","Operation":"CellLoad","Name":"MLA_NMABQ2002_31LEA","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":null,"NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"CellLoadJobResponseMessage","CellsAttempted":0,"CellsLoaded":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "2FADCF91-2C33-4E7E-B3A0-9EA38C0F2A38",
    Name: "dropfile",
    Operation: 3,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-01T20:55:47.2275607",
    InitializingTimeUtc: "2024-10-01T20:55:51.8021745",
    ChunksQueuedTimeUtc: "2024-10-01T20:55:52.0430000",
    RunningTimeUtc: "2024-10-01T20:56:00.0130000",
    AllChunksPushedTimeUtc: "2024-10-01T20:56:17.0260000",
    StoppingTimeutc: "2024-10-01T20:56:17.5900000",
    EndTimeUtc: "2024-10-01T20:56:17.7127606",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 8,
    ChunksRequeuedAtLeastOnce: 0,
    ChunksRequeuedAtLeastTwice: 0,
    ChunksSucceeded: 8,
    ChunksSkipped: 0,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 2029,
    MaxChunkCompletionMs: 2239,
    AvgChunkCompletionMs: 2122,
    MedianChunkCompletionMs: 2051,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitDropFileLoadJobMessage","DeleteSourceOnSuccess":false,"DropFileParsingPatterns":["(?i)(?\\u003Cmarket\\u003E[A-Z0-9]\\u002B)_(?\\u003Ctechnology\\u003E[A-Z0-9]\\u002B)_(?\\u003Cband\\u003E[A-Z0-9]\\u002B)\\\\.grd$"],"OutputRasterDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","DropDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\DropFileLoad","TagId":1,"Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id": "2fadcf91-2c33-4e7e-b3a0-9ea38c0f2a38","Operation":"DropFileLoad","Name":"dropfile","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"DropFileJobResponseMessage","GrdFileCount":13,"ChunkCount":8,"FailedChunkCount":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "DD828284-F5FE-4765-A1EA-9F8644AFA22C",
    Name: "test",
    Operation: 24,
    Priority: 1,
    StoppingStatus: 6,
    Status: 7,
    AllChunksPushed: false,
    SubmitTimeUtc: "2024-10-02T17:19:31.6550360",
    InitializingTimeUtc: "2024-10-02T17:19:34.2829070",
    StoppingTimeutc: "2024-10-02T17:19:34.3490000",
    EndTimeUtc: "2024-10-02T17:19:34.3621823",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    RequestJson:
      '{"$type":"SubmitCellLoadJobMessage","CellLoadingDatabaseAlias":"Main","WhereClause":"","Force":false,"OutputRasterDirectory":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\CellLoadSignalRepository","Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"between 25% 75%","Improved":null,"Maintained":"\\u003C= 0%","Degraded":"\\u003E 50%","Dropped":"\\u003E 50%"},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id":"dd828284-f5fe-4765-a1ea-9f8644afa22c","Operation":"CellLoad","Name":"test","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":null,"NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"FailedJobResponseMessage","Exception":{"TimeUtc":"2024-10-02T17:19:34.333Z","Message":"The \\u0027CellTagLoading\\u0027 table does not exist in database \\u0027differentiate\\u0027","StackTrace":[{"Method":"SGSI.MapEngines.Storage.Repositories.CellTagLoadingRepository.GetMissingTableColumns()","Path":"C:\\\\Users\\\\Richard.O\\\\OneDrive - SGSI\\\\repos\\\\mapengines2\\\\mapengines\\\\src\\\\SGSI.MapEngines.Storage\\\\Repositories\\\\CellTagLoadingRepository.cs","LineNumber":63},{"Method":"SGSI.MapEngines.Storage.Actions.CellTagInstanceAction.ValidateLoadingTable(String connectionString)","Path":"C:\\\\Users\\\\Richard.O\\\\OneDrive - SGSI\\\\repos\\\\mapengines2\\\\mapengines\\\\src\\\\SGSI.MapEngines.Storage\\\\Actions\\\\CellTagInstanceAction.cs","LineNumber":100},{"Method":"SGSI.MapEngines.Distributed.Jobs.CellLoadJob.StartJob(CancellationToken token)\\u002BMoveNext()","Path":"C:\\\\Users\\\\Richard.O\\\\OneDrive - SGSI\\\\repos\\\\mapengines2\\\\mapengines\\\\src\\\\SGSI.MapEngines.Distributed\\\\Jobs\\\\CellLoadJob.cs","LineNumber":55},{"Method":"   at System.Collections.Generic.LargeArrayBuilder\\u00601.AddRange(IEnumerable\\u00601 items)","Path":null,"LineNumber":0},{"Method":"   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable\\u00601 source)","Path":null,"LineNumber":0},{"Method":"SGSI.MapEngines.Distributed.Jobs.ChunkingJob.DoStartJob()","Path":"C:\\\\Users\\\\Richard.O\\\\OneDrive - SGSI\\\\repos\\\\mapengines2\\\\mapengines\\\\src\\\\SGSI.MapEngines.Distributed\\\\Jobs\\\\ChunkingJob.cs","LineNumber":107},{"Method":"SGSI.MapEngines.Distributed.Jobs.ChunkingJob.Process()","Path":"C:\\\\Users\\\\Richard.O\\\\OneDrive - SGSI\\\\repos\\\\mapengines2\\\\mapengines\\\\src\\\\SGSI.MapEngines.Distributed\\\\Jobs\\\\ChunkingJob.cs","LineNumber":73}],"InnerException":null},"JobStatus":"Failed"}',
    Exception:
      '{"TimeUtc":"2024-10-02T17:19:34.333Z","Message":"The \\u0027CellTagLoading\\u0027 table does not exist in database \\u0027differentiate\\u0027","StackTrace":[{"Method":"SGSI.MapEngines.Storage.Repositories.CellTagLoadingRepository.GetMissingTableColumns()","Path":"C:\\\\Users\\\\Richard.O\\\\OneDrive - SGSI\\\\repos\\\\mapengines2\\\\mapengines\\\\src\\\\SGSI.MapEngines.Storage\\\\Repositories\\\\CellTagLoadingRepository.cs","LineNumber":63},{"Method":"SGSI.MapEngines.Storage.Actions.CellTagInstanceAction.ValidateLoadingTable(String connectionString)","Path":"C:\\\\Users\\\\Richard.O\\\\OneDrive - SGSI\\\\repos\\\\mapengines2\\\\mapengines\\\\src\\\\SGSI.MapEngines.Storage\\\\Actions\\\\CellTagInstanceAction.cs","LineNumber":100},{"Method":"SGSI.MapEngines.Distributed.Jobs.CellLoadJob.StartJob(CancellationToken token)\\u002BMoveNext()","Path":"C:\\\\Users\\\\Richard.O\\\\OneDrive - SGSI\\\\repos\\\\mapengines2\\\\mapengines\\\\src\\\\SGSI.MapEngines.Distributed\\\\Jobs\\\\CellLoadJob.cs","LineNumber":55},{"Method":"   at System.Collections.Generic.LargeArrayBuilder\\u00601.AddRange(IEnumerable\\u00601 items)","Path":null,"LineNumber":0},{"Method":"   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable\\u00601 source)","Path":null,"LineNumber":0},{"Method":"SGSI.MapEngines.Distributed.Jobs.ChunkingJob.DoStartJob()","Path":"C:\\\\Users\\\\Richard.O\\\\OneDrive - SGSI\\\\repos\\\\mapengines2\\\\mapengines\\\\src\\\\SGSI.MapEngines.Distributed\\\\Jobs\\\\ChunkingJob.cs","LineNumber":107},{"Method":"SGSI.MapEngines.Distributed.Jobs.ChunkingJob.Process()","Path":"C:\\\\Users\\\\Richard.O\\\\OneDrive - SGSI\\\\repos\\\\mapengines2\\\\mapengines\\\\src\\\\SGSI.MapEngines.Distributed\\\\Jobs\\\\ChunkingJob.cs","LineNumber":73}],"InnerException":null}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "7E30EA22-680A-4BB3-9FD6-A256B1E31443",
    Name: "test",
    Operation: 24,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-02T17:14:00.9557764",
    InitializingTimeUtc: "2024-10-02T17:14:03.0420401",
    ChunksQueuedTimeUtc: "2024-10-02T17:14:03.2490000",
    RunningTimeUtc: "2024-10-02T17:14:12.8920000",
    AllChunksPushedTimeUtc: "2024-10-02T17:14:33.2550000",
    StoppingTimeutc: "2024-10-02T17:14:33.5780000",
    EndTimeUtc: "2024-10-02T17:14:33.5972894",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 5,
    ChunksRequeuedAtLeastOnce: 3,
    ChunksRequeuedAtLeastTwice: 3,
    ChunksSucceeded: 2,
    ChunksSkipped: 3,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 7,
    MaxChunkCompletionMs: 37,
    AvgChunkCompletionMs: 20,
    MedianChunkCompletionMs: 37,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitCellLoadJobMessage","CellLoadingDatabaseAlias":"ctl","WhereClause":"","Force":false,"OutputRasterDirectory":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\CellLoadSignalRepository","Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"between 25% 75%","Improved":null,"Maintained":"\\u003C= 0%","Degraded":"\\u003E 50%","Dropped":"\\u003E 50%"},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id":"7e30ea22-680a-4bb3-9fd6-a256b1e31443","Operation":"CellLoad","Name":"test","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":null,"NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"CellLoadJobResponseMessage","CellsAttempted":7,"CellsLoaded":2,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "16C00360-2AA0-4E3A-A4A2-A5891178D2BA",
    Name: "dropfile",
    Operation: 3,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-01T21:15:20.2685750",
    InitializingTimeUtc: "2024-10-01T21:15:22.3785345",
    ChunksQueuedTimeUtc: "2024-10-01T21:15:22.6380000",
    RunningTimeUtc: "2024-10-01T21:15:31.7280000",
    AllChunksPushedTimeUtc: "2024-10-01T21:15:48.9290000",
    StoppingTimeutc: "2024-10-01T21:15:49.2450000",
    EndTimeUtc: "2024-10-01T21:15:49.4916866",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 8,
    ChunksRequeuedAtLeastOnce: 0,
    ChunksRequeuedAtLeastTwice: 0,
    ChunksSucceeded: 8,
    ChunksSkipped: 0,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 2043,
    MaxChunkCompletionMs: 2420,
    AvgChunkCompletionMs: 2145,
    MedianChunkCompletionMs: 2155,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitDropFileLoadJobMessage","DeleteSourceOnSuccess":false,"DropFileParsingPatterns":["(?i)(?\\u003Cmarket\\u003E[A-Z0-9]\\u002B)_(?\\u003Ctechnology\\u003E[A-Z0-9]\\u002B)_(?\\u003Cband\\u003E[A-Z0-9]\\u002B)\\\\.grd$"],"OutputRasterDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","DropDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\DropFileLoad","TagId":1,"Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"between 25% 75%","Improved":null,"Maintained":"\\u003C= 0%","Degraded":"\\u003E 50%","Dropped":"\\u003E 50%"},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id":"16c00360-2aa0-4e3a-a4a2-a5891178d2ba","Operation":"DropFileLoad","Name":"dropfile","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"DropFileJobResponseMessage","GrdFileCount":13,"ChunkCount":8,"FailedChunkCount":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "161DF85D-F499-4D83-9E91-A5DF7EB3ABE4",
    Name: "dropfile",
    Operation: 3,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-01T19:57:05.9399926",
    InitializingTimeUtc: "2024-10-01T19:57:15.4134729",
    ChunksQueuedTimeUtc: "2024-10-01T20:13:14.0680000",
    RunningTimeUtc: "2024-10-01T20:13:20.5300000",
    AllChunksPushedTimeUtc: "2024-10-01T20:13:32.7220000",
    StoppingTimeutc: "2024-10-01T20:13:33.3900000",
    EndTimeUtc: "2024-10-01T20:13:33.4734594",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 8,
    ChunksRequeuedAtLeastOnce: 0,
    ChunksRequeuedAtLeastTwice: 0,
    ChunksSucceeded: 8,
    ChunksSkipped: 0,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 1332,
    MaxChunkCompletionMs: 1865,
    AvgChunkCompletionMs: 1516,
    MedianChunkCompletionMs: 1400,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitDropFileLoadJobMessage","DeleteSourceOnSuccess":false,"DropFileParsingPatterns":["(?i)(?\\u003Cmarket\\u003E[A-Z0-9]\\u002B)_(?\\u003Ctechnology\\u003E[A-Z0-9]\\u002B)_(?\\u003Cband\\u003E[A-Z0-9]\\u002B)\\\\.grd$"],"OutputRasterDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","DropDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\DropFileLoad","TagId":1,"Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id": "161df85d-f499-4d83-9e91-a5df7eb3abe4","Operation":"DropFileLoad","Name":"dropfile","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"DropFileJobResponseMessage","GrdFileCount":13,"ChunkCount":8,"FailedChunkCount":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "8C7AD93C-1861-4CBC-B3C9-A8EA6DA0147E",
    Name: "dropfile",
    Operation: 3,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-01T19:55:29.3311697",
    InitializingTimeUtc: "2024-10-01T19:55:43.2815457",
    ChunksQueuedTimeUtc: "2024-10-01T19:55:49.8810000",
    RunningTimeUtc: "2024-10-01T19:55:52.8330000",
    AllChunksPushedTimeUtc: "2024-10-01T19:56:04.4900000",
    StoppingTimeutc: "2024-10-01T19:56:05.1780000",
    EndTimeUtc: "2024-10-01T19:56:05.2535925",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 8,
    ChunksRequeuedAtLeastOnce: 0,
    ChunksRequeuedAtLeastTwice: 0,
    ChunksSucceeded: 8,
    ChunksSkipped: 0,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 1300,
    MaxChunkCompletionMs: 1663,
    AvgChunkCompletionMs: 1448,
    MedianChunkCompletionMs: 1396,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitDropFileLoadJobMessage","DeleteSourceOnSuccess":false,"DropFileParsingPatterns":["(?i)(?\\u003Cmarket\\u003E[A-Z0-9]\\u002B)_(?\\u003Ctechnology\\u003E[A-Z0-9]\\u002B)_(?\\u003Cband\\u003E[A-Z0-9]\\u002B)\\\\.grd$"],"OutputRasterDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","DropDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\DropFileLoad","TagId":1,"Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id": "8c7ad93c-1861-4cbc-b3c9-a8ea6da0147e","Operation":"DropFileLoad","Name":"dropfile","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"DropFileJobResponseMessage","GrdFileCount":13,"ChunkCount":8,"FailedChunkCount":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "C632182A-40E1-4F13-9363-A90FA7CB3508",
    Name: "dropfile",
    Operation: 3,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-01T19:34:35.6851390",
    InitializingTimeUtc: "2024-10-01T19:34:39.9743345",
    ChunksQueuedTimeUtc: "2024-10-01T19:38:00.7900000",
    RunningTimeUtc: "2024-10-01T19:38:10.8050000",
    AllChunksPushedTimeUtc: "2024-10-01T19:38:22.2210000",
    StoppingTimeutc: "2024-10-01T19:38:23.2110000",
    EndTimeUtc: "2024-10-01T19:38:23.2838752",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 8,
    ChunksRequeuedAtLeastOnce: 0,
    ChunksRequeuedAtLeastTwice: 0,
    ChunksSucceeded: 8,
    ChunksSkipped: 0,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 1221,
    MaxChunkCompletionMs: 1639,
    AvgChunkCompletionMs: 1417,
    MedianChunkCompletionMs: 1503,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitDropFileLoadJobMessage","DeleteSourceOnSuccess":false,"DropFileParsingPatterns":["(?i)(?\\u003Cmarket\\u003E[A-Z0-9]\\u002B)_(?\\u003Ctechnology\\u003E[A-Z0-9]\\u002B)_(?\\u003Cband\\u003E[A-Z0-9]\\u002B)\\\\.grd$"],"OutputRasterDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","DropDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\DropFileLoad","TagId":1,"Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id": "c632182a-40e1-4f13-9363-a90fa7cb3508","Operation":"DropFileLoad","Name":"dropfile","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"DropFileJobResponseMessage","GrdFileCount":13,"ChunkCount":8,"FailedChunkCount":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "15597081-F0D7-421C-B9CB-B6776F31D1F1",
    Name: "MLA_NMABQ2002_21LPA",
    Operation: 24,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: false,
    SubmitTimeUtc: "2024-10-01T15:29:42.8614412",
    InitializingTimeUtc: "2024-10-01T15:29:50.3791557",
    ChunksQueuedTimeUtc: "2024-10-01T15:29:50.6180000",
    StoppingTimeutc: "2024-10-01T15:29:50.6410000",
    EndTimeUtc: "2024-10-01T15:29:50.6661951",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 0,
    RequestJson:
      '{"$type":"SubmitCellLoadJobMessage","CellLoadingDatabaseAlias":"ctl","WhereClause":"WHERE SectorId=\\u0027MLA_NMABQ2002_21LPA\\u0027","Force":false,"OutputRasterDirectory":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\CellLoadSignalRepository","Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id":"15597081-f0d7-421c-b9cb-b6776f31d1f1","Operation":"CellLoad","Name":"MLA_NMABQ2002_21LPA","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":null,"NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"CellLoadJobResponseMessage","CellsAttempted":0,"CellsLoaded":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "CF3DBAC6-B301-4CFE-BF80-BAC5842A672D",
    Name: "cellload alias 2",
    Operation: 24,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-02T17:11:37.7934535",
    InitializingTimeUtc: "2024-10-02T17:11:43.2573882",
    ChunksQueuedTimeUtc: "2024-10-02T17:11:43.5180000",
    RunningTimeUtc: "2024-10-02T17:11:52.3090000",
    AllChunksPushedTimeUtc: "2024-10-02T17:12:12.6780000",
    StoppingTimeutc: "2024-10-02T17:12:12.7880000",
    EndTimeUtc: "2024-10-02T17:12:12.8069854",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 5,
    ChunksRequeuedAtLeastOnce: 3,
    ChunksRequeuedAtLeastTwice: 3,
    ChunksSucceeded: 2,
    ChunksSkipped: 3,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 7,
    MaxChunkCompletionMs: 30,
    AvgChunkCompletionMs: 20,
    MedianChunkCompletionMs: 30,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitCellLoadJobMessage","CellLoadingDatabaseAlias":"ctl","WhereClause":"","Force":false,"OutputRasterDirectory":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\CellLoadSignalRepository","Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"between 25% 75%","Improved":null,"Maintained":"\\u003C= 0%","Degraded":"\\u003E 50%","Dropped":"\\u003E 50%"},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id":"cf3dbac6-b301-4cfe-bf80-bac5842a672d","Operation":"CellLoad","Name":"cellload alias 2","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":null,"NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"CellLoadJobResponseMessage","CellsAttempted":7,"CellsLoaded":2,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "661DD6E7-76B6-4224-B8CF-C7ACC72143C7",
    Name: "dropfile",
    Operation: 3,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-01T20:16:14.6309512",
    InitializingTimeUtc: "2024-10-01T20:16:23.8636611",
    ChunksQueuedTimeUtc: "2024-10-01T20:16:24.1120000",
    RunningTimeUtc: "2024-10-01T20:16:33.0690000",
    AllChunksPushedTimeUtc: "2024-10-01T20:16:44.9710000",
    StoppingTimeutc: "2024-10-01T20:16:45.4810000",
    EndTimeUtc: "2024-10-01T20:16:45.5652463",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 8,
    ChunksRequeuedAtLeastOnce: 0,
    ChunksRequeuedAtLeastTwice: 0,
    ChunksSucceeded: 8,
    ChunksSkipped: 0,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 1316,
    MaxChunkCompletionMs: 1650,
    AvgChunkCompletionMs: 1482,
    MedianChunkCompletionMs: 1568,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitDropFileLoadJobMessage","DeleteSourceOnSuccess":false,"DropFileParsingPatterns":["(?i)(?\\u003Cmarket\\u003E[A-Z0-9]\\u002B)_(?\\u003Ctechnology\\u003E[A-Z0-9]\\u002B)_(?\\u003Cband\\u003E[A-Z0-9]\\u002B)\\\\.grd$"],"OutputRasterDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","DropDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\DropFileLoad","TagId":1,"Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id": "661dd6e7-76b6-4224-b8cf-c7acc72143c7","Operation":"DropFileLoad","Name":"dropfile","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"DropFileJobResponseMessage","GrdFileCount":13,"ChunkCount":8,"FailedChunkCount":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "F489637B-9B55-4D31-BF19-DE432A79B6C2",
    Name: "dropfile",
    Operation: 3,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-01T19:38:14.0515135",
    InitializingTimeUtc: "2024-10-01T19:38:23.3097877",
    ChunksQueuedTimeUtc: "2024-10-01T19:39:59.8420000",
    RunningTimeUtc: "2024-10-01T19:40:09.8390000",
    AllChunksPushedTimeUtc: "2024-10-01T19:40:21.0510000",
    StoppingTimeutc: "2024-10-01T19:40:21.1930000",
    EndTimeUtc: "2024-10-01T19:40:21.2707876",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 8,
    ChunksRequeuedAtLeastOnce: 0,
    ChunksRequeuedAtLeastTwice: 0,
    ChunksSucceeded: 8,
    ChunksSkipped: 0,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 1279,
    MaxChunkCompletionMs: 1616,
    AvgChunkCompletionMs: 1397,
    MedianChunkCompletionMs: 1481,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitDropFileLoadJobMessage","DeleteSourceOnSuccess":false,"DropFileParsingPatterns":["(?i)(?\\u003Cmarket\\u003E[A-Z0-9]\\u002B)_(?\\u003Ctechnology\\u003E[A-Z0-9]\\u002B)_(?\\u003Cband\\u003E[A-Z0-9]\\u002B)\\\\.grd$"],"OutputRasterDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","DropDirectory":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\DropFileLoad","TagId":1,"Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id": "f489637b-9b55-4d31-bf19-de432a79b6c2","Operation":"DropFileLoad","Name":"dropfile","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":"\\\\\\\\localhost\\\\C$\\\\MapEngines_AT\\\\InputFiles\\\\SignalRasters_DropFile","NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"DropFileJobResponseMessage","GrdFileCount":13,"ChunkCount":8,"FailedChunkCount":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "48A5DA17-3646-4C0E-95F4-F1F9D5CD01A2",
    Name: "cellload alias",
    Operation: 24,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: true,
    SubmitTimeUtc: "2024-10-02T17:08:37.0321574",
    InitializingTimeUtc: "2024-10-02T17:08:39.7852848",
    ChunksQueuedTimeUtc: "2024-10-02T17:08:40.1920000",
    RunningTimeUtc: "2024-10-02T17:08:49.8690000",
    AllChunksPushedTimeUtc: "2024-10-02T17:09:12.0340000",
    StoppingTimeutc: "2024-10-02T17:09:12.5560000",
    EndTimeUtc: "2024-10-02T17:09:12.6015982",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 15,
    ChunksRequeuedAtLeastOnce: 3,
    ChunksRequeuedAtLeastTwice: 3,
    ChunksSucceeded: 12,
    ChunksSkipped: 3,
    ChunksFailed: 0,
    ChunksCancelled: 0,
    MinChunkCompletionMs: 9,
    MaxChunkCompletionMs: 474,
    AvgChunkCompletionMs: 97,
    MedianChunkCompletionMs: 51,
    ChunkProcessors: 1,
    ChunkHosts: 1,
    RequestJson:
      '{"$type":"SubmitCellLoadJobMessage","CellLoadingDatabaseAlias":"ctl","WhereClause":"","Force":false,"OutputRasterDirectory":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\CellLoadSignalRepository","Reprojections":[{"Epsg":3857,"Resolution_Meters":100,"ExportTIFF":false,"Native":false},{"Epsg":0,"Resolution_Meters":0,"ExportTIFF":false,"Native":true}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"between 25% 75%","Improved":null,"Maintained":"\\u003C= 0%","Degraded":"\\u003E 50%","Dropped":"\\u003E 50%"},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id":"48a5da17-3646-4c0e-95f4-f1f9d5cd01a2","Operation":"CellLoad","Name":"cellload alias","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":null,"NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"CellLoadJobResponseMessage","CellsAttempted":17,"CellsLoaded":2,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
  {
    Id: "39DF7DF0-39AF-4EDF-A67D-FA12E102DBD8",
    Name: "MLA_NMABQ2002_21LPA",
    Operation: 24,
    Priority: 1,
    StoppingStatus: 4,
    Status: 5,
    LastPercentDone: 100,
    AllChunksPushed: false,
    SubmitTimeUtc: "2024-10-01T15:37:09.7247865",
    InitializingTimeUtc: "2024-10-01T15:37:11.4908772",
    ChunksQueuedTimeUtc: "2024-10-01T15:37:11.6950000",
    StoppingTimeutc: "2024-10-01T15:37:11.7060000",
    EndTimeUtc: "2024-10-01T15:37:11.7171217",
    Owner: "Richard.O@sgsi.com",
    ProcessorHost: "SGSI-LT21-07",
    ProcessorIndex: 0,
    OriginalChunks: 0,
    RequestJson:
      '{"$type":"SubmitCellLoadJobMessage","CellLoadingDatabaseAlias":"ctl","WhereClause":"WHERE SectorId=\\u0027MLA_NMABQ2002_31LEA\\u0027","Force":false,"OutputRasterDirectory":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\CellLoadSignalRepository","Reprojections":[{"Epsg":4326,"Resolution_Meters":100,"ExportTIFF":false,"Native":false}],"LoadMinSignal":-120,"SourceStatisticsEnabled":true,"SourceStatisticsResolution_Meters":100,"DeltaClassRules":{"Added":"","Improved":"","Maintained":"","Degraded":"","Dropped":""},"TechBandsWithBypassReview":[],"SharedReadFilePaths":[],"SharedWriteFilePaths":["SignalRasterPaths"],"Id":"39df7df0-39af-4edf-a67d-fa12e102dbd8","Operation":"CellLoad","Name":"MLA_NMABQ2002_21LPA","Priority":"Low","Cluster":null,"Owner":"Richard.O@sgsi.com","OutputPath":null,"NextJobMessages":null,"AdditionalNotifications":[],"BaseWorkingDirectoryPath":"\\\\\\\\localhost\\\\c$\\\\SGSI_Apps_Data\\\\MapEngines\\\\WorkingDirectory","PreserveWorkingDirectoryOnFailure":false,"DatabaseConnections":{"Main":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=differentiate;Connection Timeout=30;Pooling=true","OutputReports":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=MapEngines_ReportOutput;Connection Timeout=30;Pooling=true","ctl":"TrustServerCertificate=True;User ID=DevTest;Password=DevTest;Server=localhost;Database=cellload;Connection Timeout=30;Pooling=true"},"ArchiveDirectory":"","PingExpiration":"10:00:00"}',
    ResponseJson:
      '{"$type":"CellLoadJobResponseMessage","CellsAttempted":0,"CellsLoaded":0,"JobStatus":"Completed"}',
    Version: "1.0.0",
    CommitHash: "1.0.0",
  },
];
